name: CI to Docker Hub

on:
  push:
    branches:
      - master
  pull_request: ~
  workflow_dispatch: ~

jobs:
  tests:
    name: CI to Docker Hub
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_ENTRYPOINT: https://cda2-devops-hamza.simplon-roanne.com/
    steps:
      # - name: Release to Docker Hub

# jobs:
#   release:
#     runs-on: ubuntu-latest
#     steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
      # - name: Install Go
      #   uses: actions/setup-go@v2
      #   with:
      #     go-version: 1.16.4

      - name: Checkout code
        uses: actions/checkout@v2
      # - name: Push on Docker Repo 
      #   id:   docker_build 
      #   run: sudo docker push ${{ secrets.DOCKER_HUB_USERNAME }}/api-platform-devops-hamza:tagname 
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/api-platform-devops-hamza:lastest
      # - name: Build and push Docker image
      #   id:   docker_build 
      #   uses: docker/build-push-action@v2
      #   with:
      #     push: true
      #     tags: api-platform-devops-vercel:latest

      # - name: Image digest
      #   run: echo ${{ steps.docker_build.outputs.digest }}